// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zohnekkvresqlqaiuqbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvaG5la2t2cmVzcWxxYWl1cWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDQyMjcsImV4cCI6MjA2MDIyMDIyN30.Syq_EcVDI6jiuZnGgohAoVBQgjbWnxa7I_201yZk180";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
